// <auto-generated />
namespace TeleHelp.Infraestrutura.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MyBI2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MyBI2));
        
        string IMigrationMetadata.Id
        {
            get { return "201712280234420_MyBI2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
